services:
  vision-inference:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: vision-inference
    volumes:
      - ./:/app
      - /dev:/dev
    restart: always
    ports:
      - "8080:8080"
