services:
  vision-inference:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: vision-inference
    volumes:
      - ./src:app/src
    restart: always
    ports:
      - "8080:8080"
